---
title: "conditional_probability_workshop"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
```

```{r}
stroke_data <-read_csv (here("data/healthcare-dataset-stroke-data.csv"))
```

```{r}
ggplot(data = stroke_data, aes(x = gender, fill = factor(stroke))) +
  geom_bar(position = "dodge")
```

```{r}
stroke_data %>% 
  count(gender) %>% 
  mutate(percent = n / sum(n))
```

```{r}
stroke_data %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n))
```

```{r}
#first code --> will change in the next
probability_disease <- stroke_data %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke_data) %>% 
  pull(percent)
```

P(A)

probability of hypertension

```{r}
stroke_data %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n))
```

```{r}
probability_hypertension <- stroke_data %>% 
  count(hypertension) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(hypertension == "1") %>% 
  pull(percent)

probability_hypertension
```

P(B)

probability of stroke

```{r}
stroke_data %>% 
  count(stroke) %>% 
  mutate(percent = n / sum(n))
```

```{r}
probability_stroke <- stroke_data %>% 
  count(stroke) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(stroke == 1) %>% 
  pull(percent)

probability_stroke
```

P(A\|B)

probability of hypertension given stroke

```{r}
stroke_data %>% 
  count(hypertension, stroke) %>% 
  group_by(stroke) %>% 
  mutate(percent = n / sum(n))
```

```{r}
probability_hypertension_given_stroke <- stroke_data %>% 
  count(hypertension, stroke) %>% 
  group_by(hypertension) %>% 
  mutate(percent = n / sum(n)) %>% 
  filter(hypertension == 1, stroke == 1) %>% 
  pull(percent)

probability_hypertension_given_stroke
```

```{r}
(probability_hypertension_given_stroke * probability_stroke) / probability_hypertension

```
